# Generated by Django 2.0.6 on 2018-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180531_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='vote', max_length=255),
        ),
    ]
