# Generated by Django 2.0.5 on 2018-05-29 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180529_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hunter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
