# Generated by Django 2.0.5 on 2018-05-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180529_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='product_id',
        ),
    ]
