# Generated by Django 2.0.6 on 2018-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180529_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='product',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
